[package]
name = "graphql-fun"
version = "0.1.0"
authors = ["Piet Geursen <pietgeursen@gmail.com>"]
edition = "2018"

[dependencies]
juniper = "0.11.0"
juniper_warp = "0.2.0"
hyper = "0.12"
pretty_env_logger = "0.3.0"
warp = "0.1.8"
